version: '3'

x-back-build-context: &x-back-build-context ./back

x-back-build-args: &x-back-build-args
  PROJECT_NAME: vidz-back

x-back-dev: &x-back-dev
  build:
    context: *x-back-build-context
    args:
      <<: *x-back-build-args
      CACHE_ID_PREFIX: dev
      POETRY_INSTALL_WITH: dev

services:
  back:
    build:
      context: *x-back-build-context
      args:
        <<: *x-back-build-args
    develop:
      watch:
        - action: sync
          path: ./back/app
          target: /app
        - action: rebuild
          path: ./back/poetry.lock

  back-lint:
    <<: *x-back-dev
    command: black /app; isort /app; flake8 /app
    volumes:
      - ./back/app:/app