[tool.poetry]
name = "vidz"
version = "0.1.0"
description = ""
authors = ["Don Nguyen <ndon55555@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlink = "^6.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
